###
POST http://localhost:3000/api/auth/register
Content-Type: application/json
{
    "username": "Luffy",
    "email": "luffy06@gmail.com",
    "password": "strawhat"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json
{
    "email": "newemail@gmail.com",
    "password": "Kingofhell"
}






